
name: springboot2-webservice CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Make directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Copy Script
        run: cp ./scripts/*.sh ./deploy

      - name: Copy appspec
        run: cp appspec.yml ./deploy

      - name: Make zip file
        run: zip -r ./springboot2-webservice.zip ./deploy

      - name: S3 authenticaion configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 --acl private ./springboot2-webservice.zip s3://springboot2-build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name springboot2-webservice \
          --deployment-group-name springboot2-webservice-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=springboot2-build,bundleType=zip,key=springboot2-webservice.zip \
          --region ap-northeast-2
